### ISSUE TITLE
 Not a bug - info converting this mod (and other stuffs) to FS25

### ISSUE THREAD

**Issue by FirenzeIT** [GMNGjoy/FS22_SpawnPalletsStacked#3]
Hi @GMNGjoy, have you a plan for convert this mod and others stuff to FS 25?

**Comment by GMNGjoy** [comment]
100% it's coming to FS25 -  it's about #3-4 on my list right now,  with
VPW, Trickle Usage & HorseResellValue just ahead of it. Look for it in the
new year!
